FROM golang:1.24.0-bookworm

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

RUN go run github.com/playwright-community/playwright-go/cmd/playwright@latest install --with-deps

COPY . .

CMD ["go", "test", "-tags=e2e", "-v", "./tests/e2e/..."]
