FROM golang:1.25-bookworm

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

RUN go run github.com/mxschmitt/playwright-go/cmd/playwright@v0.6100.0 install --with-deps

COPY . .

CMD ["go", "test", "-tags=e2e", "-v", "./tests/e2e/..."]
